### ISSUE TITLE
Setting Filters / Permissions

### ISSUE THREAD

**Issue by rossipedia** [NFig/NFig#21]
I feel there should be a way to control which settings are allowed to be edited. The primary use case for this would be user permission based settings, where sensitive overrides would only be seen or editable by a subset of authorized users.

**Comment by bretcope** [comment]
I discussed this with Craver a little bit. I think we differ on what role NFig should play. In my mind, NFig should _not_ be responsible for enforcing permissions or filtering. I see those as the responsibility of the admin app implementation. I'm really not sure _how_ NFig would even do permissions. Different consumers are going to have different User models and I don't want to make any assumptions about their setup. I don't even want to assume that it's web-based.

However, the role I think NFig _can_ play is to provide custom metadata. Similar to how we have the `[ChangeRequiresRestart]` attribute, which is purely informational, we could provide a way to mark settings or setting groups with permission attributes and then expose that in our metadata. It would still be responsibility of the admin app to enforce them.

**Comment by bretcope** [comment]
I'm not against eventually having a library built on top of NFig that is a generic pluggable admin panel implementation with all of the APIs you need and some sort of auth model. I just don't think NFig itself is the right place to implement auth of any kind.

**Comment by rossipedia** [comment]
Yeah I was kinda thinking it needed to be one layer up from NFig. The UI probably needs to be aware of the concept of "this user can/can't see/edit this setting", but that's orthagonal to NFig itself.

At the app level, it might be as simple as exposing a `Func<SettingInfo, bool>` property that can be set that's used to filter settings / authorize overrides. The concrete implemention will probably take a clearer shape as the UI gets built.
